feat(ci/cd): updated cd.yaml with deploying database update

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -27,8 +27,16 @@ jobs:
               - 'backend/recommendation-model/api/**'
             auth:
               - 'backend/user-api/**'
-            database:
-              - 'backend/database/**'
+            database-migration:
+              - 'backend/database/models/**'
+              - 'backend/database/alembic/**'
+              - 'backend/database/db_migration_lambda_handler.py'
+              - 'backend/database/Dockerfile.db_migration'
+            movie-data-database-table-update:
+              - 'backend/database/update_movie_table_lambda_handler.py'
+              - 'backend/database/Dockerfile.update_movie_tables'
+              - 'backend/database/utils/'
+            
   deploy-frontend:
     needs: detect_changes
     if: needs.detect_changes.outputs.frontend == 'true'
@@ -167,9 +175,9 @@ jobs:
             --service auth-service \
             --region us-west-1
 
-  deploy-database:
+  deploy-database-migration:
     needs: detect_changes
-    if: needs.detect_changes.outputs.database == 'true'
+    if: needs.detect_changes.outputs.database-migration == 'true'
     runs-on: ubuntu-latest
     timeout-minutes: 15
     steps: 
@@ -194,7 +202,7 @@ jobs:
           IMAGE_TAG: ${{ github.sha }}
         working-directory: backend/database
         run: |
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.db_migration .
           docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
@@ -210,6 +218,60 @@ jobs:
         run: |
           aws lambda invoke \
             --function-name cinesense-db-migration \
+            --region us-west-1 \
+            --log-type Tail \
+            response.json
+
+            cat response.json
+
+            if grep -q "errorMessage" response.json; then
+              echo "Migration failed!"
+              exit 1
+            fi
+
+  deploy-movie-data-table-update:
+    needs: detect_changes
+    if: needs.detect_changes.outputs.movie-data-database-table-update == 'true'
+    runs-on: ubuntu-latest
+    timeout-minutes: 15
+    steps: 
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: set aws credentials
+        uses: aws-actions/configure-aws-credentials@v5.0.0
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_BACKEND }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_BACKEND }}
+          aws-region: us-west-1
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+      
+      - name: Build and push database update Docker Image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: cinesense-database-update
+          IMAGE_TAG: ${{ github.sha }}
+        working-directory: backend/database
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.update_movie_tables .
+          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
+        
+      - name: Update Lambda Function
+        run: |
+          aws lambda update-function-code \
+            --function-name cinesense-update-movie-data-tables \
+            --image-uri ${{ steps.login-ecr.outputs.registry }}/cinesense-database-update:${{ github.sha }} \
+            --region us-west-1
+
+      - name: Invoke lambda to run migrations
+        run: |
+          aws lambda invoke \
+            --function-name cinesense-update-movie-data-tables \
             --region us-west-1 \
             --log-type Tail \
             response.json
